name: "Web Application Guidelines"

markdown: kramdown
highlighter: rouge
exclude: []
baseurl: /wag-external-v4
cdn_url: //assets.malmo.se/external/v4
permalink: /:categories/:title
relative_permalinks: false

sass:
  # style: :expanded
  style: :compressed

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
